# Generated by Django 4.0.4 on 2022-04-21 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_post_postcategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='images',
            field=models.ImageField(default=0, upload_to='images/', verbose_name='Изображение'),
        ),
    ]
