# Generated by Django 4.0.4 on 2022-04-23 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_author_options_alter_category_options_and_more'),
        ('news', '0003_post_images'),
    ]

    operations = [
    ]
