# Generated by Django 4.0.4 on 2022-04-23 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_merge_20220423_1339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='images',
        ),
    ]
