# Generated by Django 4.0.4 on 2022-04-25 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_remove_post_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='dateCreation',
            field=models.DateTimeField(blank=True, null=True, verbose_name='дата'),
        ),
    ]
